# Generated by Django 4.2.6 on 2023-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_login',
            field=models.CharField(default='Алексей', max_length=200),
            preserve_default=False,
        ),
    ]
