# Generated by Django 4.2.6 on 2023-10-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_recipe_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='Алексей', max_length=200, verbose_name='имя автора'),
            preserve_default=False,
        ),
    ]
